# -*- coding: utf-8 -*-
"""45.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ve3Rzjg1shmqgOBoM4RFVCKJrK0H-kRI
"""

# ==== 45° Uptrend Finder (SPX + NDX) — Colab Ready ====
# Adds: earnings-within-N-days filter, $dollar-volume filter, optional Streamlit UI via ngrok
!pip -q install yfinance pandas numpy scipy streamlit pyngrok pycloudflared
# !pip -q install yfinance pandas numpy scipy streamlit pycloudflared



import os, math, time, threading, textwrap, datetime as dt
import numpy as np
import pandas as pd
import yfinance as yf
from scipy.stats import linregress
import requests
from google.colab import userdata
from pyngrok import ngrok

from pycloudflared import try_cloudflare
import subprocess

# -----------------------
# USER TOGGLES
# -----------------------
EARNINGS_WINDOW_DAYS = 7        # skip tickers with earnings within this many calendar days
MIN_DOLLAR_VOLUME = 20_000_000  # min avg daily $ volume (price * volume) over 30 trading days
PASS_SCORE = 70                 # score threshold
RUN_STREAMLIT = True           # set True to launch a simple UI inside Colab using ngrok
# NGROK_AUTH_TOKEN = ""           # optional, paste your token to avoid time-limited tunnels
# NGROK_AUTH_TOKEN = "XXX"

TUNNEL_MODE = "auto"

# Fetch from Colab secrets
token = userdata.get("NGROK_AUTH_TOKEN")

# os.environ["NGROK_AUTH_TOKEN"] = "XXXX"
# Make it available as an environment variable
os.environ["NGROK_AUTH_TOKEN"] = token


NGROK_AUTH_TOKEN = os.environ.get("NGROK_AUTH_TOKEN", "")
if NGROK_AUTH_TOKEN:
    ngrok.set_auth_token(NGROK_AUTH_TOKEN)

SCAN_PERIOD = "420d"            # price history window for indicators
SCAN_INTERVAL = "1d"            # daily bars
UNIVERSE_SOURCES = ("SPX", "NDX")  # which universes to include


# --- 1) Hand-editable list you control ---
# MORE_TICKERS = [
#     "SOFI",  "OKTA", "MSTR" # add anything else here later: "OKTA", "MSTR", ...
# ]

MORE_TICKERS = [t.strip().upper().replace(".", "-") for t in [
    "SOFI", "OKTA", "MSTR", "BMNR", "SSK"
]]



# ---- NEW: permanent watchlist you care about ----
MYLIST = [t.strip().upper().replace(".", "-") for t in [
     "TSLA",
    "MSTR",
    "NVDA",
    "GOOG",
    "PLTR",
    "BMNR",
    "BE",
    "MU",
    "IREN",
    "CRDO",
    "AVGO",
    "TSM",
    "SOFI",
    "AMD",
    "APP",
    "COIN",
    "LEU",
    "HOOD",
    "OKLO",
    "CRVW",
    "MP",
    "INOD",
    "CFG",
    "APLD",
    "AAOI",
    "CORZ",
    "UPXI",
    "STKE"
]]
MYLIST_SET = set(MYLIST)


# -----------------------
# Helper funcs
# -----------------------
def ema(s, n): return s.ewm(span=n, adjust=False, min_periods=n).mean()
def sma(s, n): return s.rolling(n, min_periods=n).mean()

def true_range(h, l, c):
    pc = c.shift(1)
    return pd.concat([h-l, (h-pc).abs(), (l-pc).abs()], axis=1).max(axis=1)

def atr(h, l, c, n=14):
    return true_range(h, l, c).rolling(n, min_periods=n).mean()

# def monthly_pivots(df):
#     m = df.resample("ME").agg({"High":"max","Low":"min","Close":"last"})
#     if len(m) < 2: return (np.nan, np.nan, np.nan)
#     prev = m.iloc[-2]
#     P = (prev.High + prev.Low + prev.Close)/3.0
#     R1 = 2*P - prev.Low
#     R2 = P + (prev.High - prev.Low)
#     return (P, R1, R2)

def monthly_pivots(df):
    m = df.resample("ME").agg({"High":"max","Low":"min","Close":"last"})
    if len(m) < 2:
        return (np.nan,)*7
    prev = m.iloc[-2]
    P = (prev.High + prev.Low + prev.Close)/3.0
    R1 = 2*P - prev.Low
    S1 = 2*P - prev.High
    R2 = P + (prev.High - prev.Low)
    S2 = P - (prev.High - prev.Low)
    R3 = prev.High + 2*(P - prev.Low)
    S3 = prev.Low - 2*(prev.High - P)
    return (P,R1,R2,R3,S1,S2,S3)



def fib_levels_236_382_500_hi(df, lookback=252):
    span = df.tail(lookback) if len(df) >= lookback else df
    hi = span["High"].max(); lo = span["Low"].min()
    if pd.isna(hi) or pd.isna(lo) or hi <= lo:
        return (np.nan, np.nan, np.nan, np.nan)
    f236 = hi - 0.236*(hi-lo)
    f382 = hi - 0.382*(hi-lo)
    f500 = hi - 0.500*(hi-lo)
    return (f236, f382, f500, hi)

def fib_levels_all(df, lookback=252):
    span = df.tail(lookback) if len(df) >= lookback else df
    hi = span["High"].max()
    lo = span["Low"].min()
    if pd.isna(hi) or pd.isna(lo) or hi <= lo:
        # 0%(Hi), 23.6, 38.2, 50, 61.8, 78.6, 100%(Lo)
        return (np.nan,)*7
    f236 = hi - 0.236*(hi-lo)
    f382 = hi - 0.382*(hi-lo)
    f500 = hi - 0.500*(hi-lo)
    f618 = hi - 0.618*(hi-lo)
    f786 = hi - 0.786*(hi-lo)
    return hi, f236, f382, f500, f618, f786, lo



def regression_stats(close, window=120, log=True):
    y = close.tail(window)
    if len(y.dropna()) < window: return (np.nan, np.nan)
    if log: y = np.log(y)
    x = np.arange(len(y))
    r = linregress(x, y)
    return (float(r.slope), float(r.rvalue**2))

def returns_over_period(close, days=63):
    if len(close.dropna()) < days+1: return np.nan
    return float((close.iloc[-1]/close.iloc[-days-1] - 1)*100.0)

def percent_above(close, ref, window=60):
    z = close.tail(window); r = ref.reindex_like(close).tail(window)
    if len(z.dropna()) < window or len(r.dropna()) < window: return np.nan
    return float((z > r).mean()*100.0)

def max_dd_from_high(close, window=120):
    y = close.tail(window)
    if len(y.dropna()) < window: return np.nan
    rm = y.cummax()
    return float((y/rm - 1).min()*100.0)  # negative %

def avg_dollar_vol(df, days=30):
    """Avg( Close * Volume ) over last N sessions."""
    if "Volume" not in df.columns: return np.nan
    c = df["Close"].tail(days); v = df["Volume"].tail(days)
    if len(c.dropna())<days or len(v.dropna())<days: return np.nan
    return float((c*v).mean())

def earnings_within_window(ticker, days=7):
    """
    Try yfinance endpoints to find the next earnings date.
    Return True if within `days` calendar days from today.
    """
    try:
        tk = yf.Ticker(ticker)
        # Preferred: get_earnings_dates
        ed = tk.get_earnings_dates(limit=1)
        if ed is not None and len(ed) > 0:
            next_dt = pd.to_datetime(ed.index[0]).to_pydatetime()
            delta = (next_dt.date() - dt.date.today()).days
            return (delta is not None) and (delta >= 0) and (delta <= days)
    except Exception:
        pass
    try:
        # Fallback: .calendar DataFrame (not always available)
        cal = yf.Ticker(ticker).calendar
        if isinstance(cal, pd.DataFrame) and "Earnings Date" in cal.index:
            raw = cal.loc["Earnings Date"].values
            # calendar sometimes returns an array of two timestamps [start, end]
            if len(raw)>0:
                nxt = pd.to_datetime(raw[0]).to_pydatetime()
                delta = (nxt.date() - dt.date.today()).days
                return (delta is not None) and (delta >= 0) and (delta <= days)
    except Exception:
        pass
    return False  # unknown = let it pass (or set True to be stricter)

# -----------------------
# Universe (SPX + NDX via Wikipedia)
# -----------------------
# def _read_html_with_headers(url: str):
#     hdrs = {
#         "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
#                       "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
#     }
#     html = requests.get(url, headers=hdrs, timeout=20)
#     html.raise_for_status()
#     return pd.read_html(html.text)


from io import StringIO

def _read_html_with_headers(url: str):
    hdrs = {
        "User-Agent": (
            "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
            "(KHTML, like Gecko) Chrome/124.0 Safari/537.36"
        )
    }
    html = requests.get(url, headers=hdrs, timeout=20)
    html.raise_for_status()
    return pd.read_html(StringIO(html.text))



# def get_spx():
#     """Get S&P 500 tickers from Wikipedia (robust to 403)."""
#     tables = _read_html_with_headers("https://en.wikipedia.org/wiki/List_of_S%26P_500_companies")
#     return tables[0]["Symbol"].str.replace(".", "-", regex=False).tolist()

def get_spx():
    """Get S&P 500 tickers from Wikipedia (robust to table/column changes)."""
    tables = _read_html_with_headers(
        "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    )

    for tbl in tables:
        cols = [str(c).strip() for c in tbl.columns]

        # Most common case
        if "Symbol" in cols:
            return (
                tbl["Symbol"]
                .astype(str)
                .str.strip()
                .str.replace(".", "-", regex=False)
                .tolist()
            )

        # Just in case they rename it
        if "Ticker" in cols:
            return (
                tbl["Ticker"]
                .astype(str)
                .str.strip()
                .str.replace(".", "-", regex=False)
                .tolist()
            )

    # If nothing matched, fail loudly so you see it
    raise RuntimeError("Could not find Symbol/Ticker column in SPX Wikipedia tables")




def get_ndx():
    """Get Nasdaq-100 tickers from Wikipedia (robust to 403)."""
    tables = _read_html_with_headers("https://en.wikipedia.org/wiki/Nasdaq-100")
    # Different revisions put it in different tables; find the right one
    for tbl in tables:
        if "Ticker" in tbl.columns:
            return tbl["Ticker"].str.replace(".", "-", regex=False).tolist()
        if "Symbol" in tbl.columns:  # fallback
            return tbl["Symbol"].str.replace(".", "-", regex=False).tolist()
    return []



# Choose universes
# UNIVERSE_SOURCES = ("SPX", "NDX")
# UNIVERSE = sorted(set([*SPX, *NDX, *MORE_TICKERS]))
uni = []
if "SPX" in UNIVERSE_SOURCES:
    uni += get_spx()
if "NDX" in UNIVERSE_SOURCES:
    uni += get_ndx()

# Final universe
# UNIVERSE = sorted(set(uni + MORE_TICKERS))
UNIVERSE = sorted(set(uni + MORE_TICKERS + MYLIST))

# --- Debug: check if SOFI (or others) are in the universe ---
print("Final universe contains:", len(UNIVERSE))
print("SOFI in universe?", "SOFI" in UNIVERSE)
print("First 10 tickers:", UNIVERSE[:10])  # optional, quick peek

# Cleanup
blacklist = {"BRK.B", "BF.B"}  # odd Yahoo tickers, handled separately
# universe = sorted({t for t in uni if t not in blacklist})
universe = sorted({t for t in UNIVERSE if t not in blacklist})
print(f"Universe size: {len(universe)}")

# Include SPY for RS baseline
tickers = sorted(set(universe + ["SPY"]))
print(f"Universe size: {len(universe)} | Downloading {len(tickers)} tickers…")

data = yf.download(tickers, period=SCAN_PERIOD, interval=SCAN_INTERVAL,
                   auto_adjust=False, progress=True, group_by='ticker')

def get_ohlc(t):
    if isinstance(data.columns, pd.MultiIndex):
        df = data[t].copy()
    else:
        df = data.copy()
    return df[["Open","High","Low","Close","Volume"]].dropna()

spy = get_ohlc("SPY")

# -----------------------
# Scoring weights/thresholds
# -----------------------
WEIGHTS = dict(ma_stack=20, ma_slopes=15, regression=25, rs=15, atrp=15, above50=10)
ATR_PCT_MAX = 5.0
R2_MIN = 0.60
RS_BONUS = 10.0
ABOVE50_MIN = 80.0

rows = []
for t in universe:
    try:
        df = get_ohlc(t)
        if df.empty or len(df) < 220:
            print(f"Skipping {t} — no data")
            continue

        # Liquidity filter — avg $ volume
        adv = avg_dollar_vol(df, 30)
        if pd.isna(adv) or adv < MIN_DOLLAR_VOLUME:
            continue

        # Earnings filter
        try:
            if EARNINGS_WINDOW_DAYS > 0 and earnings_within_window(t, EARNINGS_WINDOW_DAYS):
                continue
        except Exception:
            pass

        h,l,c = df["High"], df["Low"], df["Close"]
        ema21 = ema(c,21); sma50 = sma(c,50); sma100 = sma(c,100); sma200 = sma(c,200)
        latest = pd.concat([ema21,sma50,sma100,sma200],axis=1).tail(1).values.flatten()
        if np.any(np.isnan(latest)): continue

        ma_stack_ok = (latest[0] > latest[1] > latest[2] > latest[3])

        def rising(s, look=20):
            if len(s.dropna()) <= look: return False
            return s.iloc[-1] > s.iloc[-look-1]
        slopes_ok = all(rising(x) for x in (ema21,sma50,sma100,sma200))

        reg_slope, reg_r2 = regression_stats(c, window=120, log=True)

        rs_stock = returns_over_period(c,63)
        rs_spy = returns_over_period(spy["Close"],63)
        rs_diff = (rs_stock - rs_spy) if pd.notna(rs_stock) and pd.notna(rs_spy) else np.nan

        a = atr(h,l,c,14)
        atr_pct = float((a.iloc[-1]/c.iloc[-1])*100.0) if pd.notna(a.iloc[-1]) else np.nan
        pct_above50 = percent_above(c, sma50, 60)
        dd120 = max_dd_from_high(c, 120)

        # Pm,R1m,R2m = monthly_pivots(df)
        Pm, R1m, R2m, R3m, S1m, S2m, S3m = monthly_pivots(df)
        # F236,F382,F500,F0 = fib_levels_236_382_500_hi(df,252)
        F0hi, F236, F382, F500, F618, F786, Flo = fib_levels_all(df, 252)
        dist_21 = (c.iloc[-1]/ema21.iloc[-1]-1)*100.0
        dist_50 = (c.iloc[-1]/sma50.iloc[-1]-1)*100.0

        # Score
        score = 0.0
        if ma_stack_ok: score += WEIGHTS["ma_stack"]
        if slopes_ok:   score += WEIGHTS["ma_slopes"]
        if pd.notna(reg_slope) and pd.notna(reg_r2) and reg_slope>0 and reg_r2>=R2_MIN:
            score += WEIGHTS["regression"] * min(1.0, (reg_r2 - R2_MIN)/(1.0 - R2_MIN))
        if pd.notna(rs_diff) and rs_diff>0:
            score += WEIGHTS["rs"] * min(1.0, rs_diff/RS_BONUS)
        if pd.notna(atr_pct):
            if atr_pct <= ATR_PCT_MAX:
                score += WEIGHTS["atrp"]
            else:
                dec = max(0.0, min(1.0, 1.0 - (atr_pct - ATR_PCT_MAX)/5.0))
                score += WEIGHTS["atrp"] * dec
        if pd.notna(pct_above50):
            if pct_above50 >= ABOVE50_MIN:
                score += WEIGHTS["above50"]
            elif pct_above50 > 60:
                frac = (pct_above50 - 60.0)/(ABOVE50_MIN - 60.0)
                score += WEIGHTS["above50"] * max(0.0, min(1.0, frac))

        hint = []
        if -1.0 <= dist_21 <= 3.0: hint.append("21-EMA ready")
        if -3.0 <= dist_50 <= 1.0: hint.append("50-SMA ready")
        buy_hint = " & ".join(hint)

        stop_hint = f"{(a.iloc[-1]):.2f} (~ATR$); consider 0.5–1.0× ATR below ref" if pd.notna(a.iloc[-1]) else ""

        # --- Company Name Lookup (inside main try block) ---
        try:
            info = yf.Ticker(t).info
            company_name = info.get("longName") or info.get("shortName") or ""
        except Exception:
            company_name = ""


        rows.append({
            "Ticker": t,
             "Company": company_name,   # ← NEW
            "Score": round(score,2), "Price": float(c.iloc[-1]),
            "Dist_to_21EMA_%": round(dist_21,2), "Dist_to_50SMA_%": round(dist_50,2),
            "ATR14_$": round(float(a.iloc[-1]),2) if pd.notna(a.iloc[-1]) else np.nan,
            "ATR14_%": round(atr_pct,2) if pd.notna(atr_pct) else np.nan,
            "RS_63d_vs_SPY_%": round(rs_diff,2) if pd.notna(rs_diff) else np.nan,
            "%Closes>50SMA_60d": round(pct_above50,1) if pd.notna(pct_above50) else np.nan,
            "MaxDD_from_120dHigh_%": round(dd120,1) if pd.notna(dd120) else np.nan,
            "Monthly_Pivot": round(Pm,2) if pd.notna(Pm) else np.nan,
            "Monthly_R1": round(R1m,2) if pd.notna(R1m) else np.nan,
            "Monthly_R2": round(R2m,2) if pd.notna(R2m) else np.nan,
            "Monthly_R3":    round(R3m,2) if pd.notna(R3m) else np.nan,
            "Monthly_S1": round(S1m,2) if pd.notna(S1m) else np.nan,
            "Monthly_S2": round(S2m,2) if pd.notna(S2m) else np.nan,
            "Monthly_S3": round(S3m,2) if pd.notna(S3m) else np.nan,
            "Fib0%(Hi)": round(F0hi,2) if pd.notna(F0hi) else np.nan,
            "Fib23.6":   round(F236,2) if pd.notna(F236) else np.nan,
            "Fib38.2":   round(F382,2) if pd.notna(F382) else np.nan,
            "Fib50.0":   round(F500,2) if pd.notna(F500) else np.nan,
            "Fib61.8":   round(F618,2) if pd.notna(F618) else np.nan,
            "Fib78.6":   round(F786,2) if pd.notna(F786) else np.nan,
            "Fib100%(Lo)": round(Flo,2) if pd.notna(Flo) else np.nan,
            "Buy_Hint": buy_hint, "Stop_Hint": stop_hint,
            "Avg_$Vol_30d": round(adv,0) if not pd.isna(adv) else np.nan,
            "In_MyList": t in MYLIST_SET,   # <--- NEW FLAG
        })
    except Exception:
        print(f"Error with {t}: {e}")
        pass

df = pd.DataFrame(rows).sort_values(["Score","RS_63d_vs_SPY_%"], ascending=[False,False]).reset_index(drop=True)
top = df[df["Score"] >= PASS_SCORE].copy()
# ---- NEW: MyList-only view ----
mylist_df = df[df["Ticker"].isin(MYLIST_SET)].copy().reset_index(drop=True)

from IPython.display import display
print(f"Scanned {len(universe)} tickers.  Liquidity ≥ ${MIN_DOLLAR_VOLUME:,.0f}/day.  Earnings skip ≤ {EARNINGS_WINDOW_DAYS} days.")
print(f"Candidates with Score ≥ {PASS_SCORE}: {len(top)}\n")
display(top.head(25))

df.to_csv("uptrend_finder_full.csv", index=False)
top.to_csv("uptrend_finder_top.csv", index=False)
mylist_df.to_csv("uptrend_finder_mylist.csv", index=False)   # NEW
print("\nSaved:")
print(" - uptrend_finder_full.csv")
print(" - uptrend_finder_top.csv")
print(" - uptrend_finder_mylist.csv  (your MyList watchlist)")

!pkill -f ngrok || true

# -----------------------
# Optional Streamlit App (served inside Colab via ngrok)
# -----------------------
if RUN_STREAMLIT:
    from pyngrok import ngrok
    if NGROK_AUTH_TOKEN:
        ngrok.set_auth_token(NGROK_AUTH_TOKEN)

    # 1) Kill any lingering processes/tunnels from previous runs
    try:
        ngrok.kill()
    except Exception:
        pass
    # write a minimal app that reads the CSVs
#     app_code = """
# import pandas as pd
# import streamlit as st

# st.set_page_config(page_title="Uptrend Finder", layout="wide")
# st.title("45° Uptrend Finder — SPX + NDX")

# full = pd.read_csv("uptrend_finder_full.csv")
# top  = pd.read_csv("uptrend_finder_top.csv")

# st.sidebar.header("Filters")
# min_score = st.sidebar.slider("Min Score", 0, 100, 70, 1)
# min_rs    = st.sidebar.slider("Min RS vs SPY (63d) %", -50, 50, 0, 1)
# max_atrp  = st.sidebar.slider("Max ATR% (smoothness)", 0.0, 15.0, 5.0, 0.1)
# only_buy  = st.sidebar.checkbox("Only 'Buy Ready' (21/50 hints)", value=False)

# view = full.copy()
# view = view[(view["Score"]>=min_score) & (view["RS_63d_vs_SPY_%"]>=min_rs) & (view["ATR14_%"]<=max_atrp)]
# if only_buy:
#     view = view[view["Buy_Hint"].str.len()>0]

# st.subheader("Top (Score ≥ threshold)")
# st.dataframe(top)

# st.subheader("Filtered View")
# st.dataframe(view)
#     """.strip()

    app_code = """
import pandas as pd
import streamlit as st
import numpy as np
import yfinance as yf

st.set_page_config(page_title="Uptrend Finder", layout="wide")
st.title("45° Uptrend Finder — SPX + NDX")

# ---- Trend Score Legend (Top-Right) ----
legend_html = '''
<div style="
    position: absolute;
    top: -10px;  /* 🔼 Move legend higher */
    right: 20px;
    background-color: #f8f9fa;
    padding: 12px 15px;
    border-radius: 8px;
    border: 1px solid #ddd;
    font-size: 15px;
    line-height: 1.5;
    z-index: 999;
">
<b>Trend Score Legend</b><br>
<span style="color:#2ECC71;">🟩 90–100 → Excellent Trend</span><br>
<span style="color:#F1C40F;">🟨 70–89 → Decent / Improving</span><br>
<span style="color:#E74C3C;">🟥 Below 70 → Weak Trend</span>
</div>
'''


st.markdown(legend_html, unsafe_allow_html=True)

full = pd.read_csv("uptrend_finder_full.csv")
top  = pd.read_csv("uptrend_finder_top.csv")
mylist = pd.read_csv("uptrend_finder_mylist.csv")


st.sidebar.header("Filters")
min_score = st.sidebar.slider("Min Score", 0, 100, 70, 1)
min_rs    = st.sidebar.slider("Min RS vs SPY (63d) %", -50, 50, 0, 1)
max_atrp  = st.sidebar.slider("Max ATR% (smoothness)", 0.0, 15.0, 5.0, 0.1)
only_buy  = st.sidebar.checkbox("Only 'Buy Ready' (21/50 hints)", value=False)

view = full.copy()
view = view[(view["Score"]>=min_score) & (view["RS_63d_vs_SPY_%"]>=min_rs) & (view["ATR14_%"]<=max_atrp)]
if only_buy:
    view = view[view["Buy_Hint"].str.len()>0]

st.subheader("Top (Score ≥ threshold)")
st.dataframe(top)

st.subheader("Filtered View")
st.dataframe(view)

# -----------------------
# MyList watchlist section
# -----------------------
st.subheader("MyList Watchlist (your custom tickers)")
if mylist.empty:
    st.info("No MyList tickers passed the data/volume filters this run.")
else:
    st.dataframe(mylist)

# -----------------------
# Full ranked list
# -----------------------
st.subheader("Full Ranked List (All tickers, no filters)")
st.dataframe(full)

# --- Extra Ticker Lookup (Option B) ---
extras_raw = st.sidebar.text_input(
    "Extra tickers (comma-separated, quick lookup only)",
    value="BMNR",
    help="Shown even if they fail your filters."
)
extras_ui = [x.strip().upper() for x in extras_raw.split(",") if x.strip()]

if extras_ui:
    st.subheader("Extra Ticker(s) Lookup")
raw = st.sidebar.text_input("Extra tickers (comma-separated, quick lookup only)", value="")
tickers = [t.strip().upper().replace(".", "-") for t in raw.split(",") if t.strip()]

if tickers:
    # show any that were already in the CSVs
    in_csv = full[full["Ticker"].isin(tickers)]
    if not in_csv.empty:
        st.markdown("**Found in CSV (from your latest scan):**")
        st.dataframe(in_csv)

    # fetch any missing on the fly
    missing = [t for t in tickers if t not in set(full["Ticker"])]
    if missing:
        st.markdown("**Quick lookup (fetched now):**")
        rows = []
        for t in missing:
            try:
                df = yf.download(t, period="420d", interval="1d", progress=False, auto_adjust=False)
                if df.empty:
                    continue
                df = df[["Open","High","Low","Close","Volume"]].dropna()
                c,h,l = df["Close"], df["High"], df["Low"]

                # mini metrics (same as scanner but lighter)
                ema21 = c.ewm(span=21, adjust=False, min_periods=21).mean()
                sma50 = c.rolling(50, min_periods=50).mean()

                prev_m = df.resample("ME").agg({"High":"max","Low":"min","Close":"last"})
                Pm = R1m = R2m = np.nan
                if len(prev_m) >= 2:
                    pm = prev_m.iloc[-2]
                    Pm = (pm.High + pm.Low + pm.Close)/3.0
                    R1m = 2*Pm - pm.Low
                    R2m = Pm + (pm.High - pm.Low)

                span = df.tail(252)
                hi, lo = span["High"].max(), span["Low"].min()
                F236 = hi - 0.236*(hi-lo) if hi>lo else np.nan

                tr = pd.concat([h-l, (h-c.shift()).abs(), (l-c.shift()).abs()], axis=1).max(axis=1)
                atr14 = tr.rolling(14, min_periods=14).mean().iloc[-1]
                atrp = (atr14 / c.iloc[-1])*100 if pd.notna(atr14) else np.nan

                dist21 = (c.iloc[-1]/ema21.iloc[-1]-1)*100 if pd.notna(ema21.iloc[-1]) else np.nan
                dist50 = (c.iloc[-1]/sma50.iloc[-1]-1)*100 if pd.notna(sma50.iloc[-1]) else np.nan

                hint = []
                if pd.notna(dist21) and -1 <= dist21 <= 3: hint.append("21-EMA ready")
                if pd.notna(dist50) and -3 <= dist50 <= 1: hint.append("50-SMA ready")

                rows.append({
                    "Ticker": t, "Price": float(c.iloc[-1]),
                    "Dist_to_21EMA_%": round(dist21,2) if pd.notna(dist21) else np.nan,
                    "Dist_to_50SMA_%": round(dist50,2) if pd.notna(dist50) else np.nan,
                    "ATR14_$": round(float(atr14),2) if pd.notna(atr14) else np.nan,
                    "ATR14_%": round(float(atrp),2) if pd.notna(atrp) else np.nan,
                    "Monthly_Pivot": round(Pm,2) if pd.notna(Pm) else np.nan,
                    "Monthly_R1": round(R1m,2) if pd.notna(R1m) else np.nan,
                    "Monthly_R2": round(R2m,2) if pd.notna(R2m) else np.nan,
                    "Fib23.6": round(F236,2) if pd.notna(F236) else np.nan,
                    "Buy_Hint": " & ".join(hint),

                })
            except Exception:
                pass

        if rows:
            st.dataframe(pd.DataFrame(rows))
        else:
            st.info("No data returned for the requested tickers.")
else:
    st.info("Enter comma-separated symbols in the sidebar to look up tickers not in your universe.")
      """.strip()


    with open("app.py","w") as f:
        f.write(app_code)

    # launch streamlit
    # def run_app():
    #     os.system("streamlit run app.py --server.port 8501 >/dev/null 2>&1")
    # thread = threading.Thread(target=run_app, daemon=True); thread.start()
    # time.sleep(2)

    if not os.environ.get("STREAMLIT_RUNNING"):
        os.environ["STREAMLIT_RUNNING"] = "1"
        def run_app():
            os.system("streamlit run app.py --server.port 8501 >/dev/null 2>&1")
        th = threading.Thread(target=run_app, daemon=True); th.start()
        time.sleep(2)  # give it a moment to boot


    # from pyngrok import ngrok
    # # ngrok.kill()   # closes any old tunnels

    # # 2) Double-check and disconnect any tunnels (belt & suspenders)
    # try:
    #     for t in ngrok.get_tunnels():
    #         ngrok.disconnect(t.public_url)
    # except Exception:
    #     pass

    # public_url = ngrok.connect(8501, "http").public_url
    # print(f"\nStreamlit app is live at: {public_url}\n(Keep this Colab cell running.)")

"""## if NGROK does not work"""

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb
!cloudflared tunnel --url http://localhost:8501 --no-autoupdate

import os, shutil, subprocess, threading, re, time

def start_cloudflared(port=8501):
    """Start a Cloudflare tunnel to the given local port and print the public URL."""
    # 1) Install cloudflared if needed
    if not shutil.which("cloudflared"):
        print("Installing cloudflared...")
        subprocess.run(
            "wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb",
            shell=True,
            check=True,
        )
        subprocess.run(
            "dpkg -i cloudflared-linux-amd64.deb",
            shell=True,
            check=True,
        )

    # 2) Start the tunnel in a background thread and capture the URL
    def _run():
        cmd = f"cloudflared tunnel --url http://localhost:{port} --no-autoupdate"
        # merge stdout & stderr so we only read one stream
        with subprocess.Popen(
            cmd.split(),
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        ) as p:
            for line in p.stdout:
                # Look for the trycloudflare URL line
                if "trycloudflare.com" in line:
                    m = re.search(r"https://[^\s]+", line)
                    if m:
                        url = m.group(0)
                        print(f"\nStreamlit app is live at: {url}\n(Keep this Colab cell running.)")
                    else:
                        print("\nCloudflare tunnel started, check above logs for the URL.\n")
                    # we keep the process running so the tunnel stays alive
            p.wait()

    threading.Thread(target=_run, daemon=True).start()

# ---- call it after Streamlit has started ----
# start_cloudflared(port=8501)

